user_name: server
user_group: "{{ user_name }}"
admin_name: "{{ ansible_user | default ('admin') }}"
backup_conf: false
test: false

# vault variables (to be defined and encrypted in `vault.yml`)
external_media_path: "{{ vault_external_media_path }}"
ubuntu_advantage_token: "{{ vault_ubuntu_advantage_token }}"
timezone: "{{ vault_timezone }}"
telegram_url: "{{ vault_telegram_url }}"
borg_passphrase: "{{ vault_borg_passphrase }}"
mail_host: "{{ vault_mail_host }}"
mail_user: "{{ vault_mail_user }}"
mail_password: "{{ vault_mail_password }}"
ddns_server: "{{ vault_ddns_server }}"
ddns_users: "{{ vault_ddns_users }}"
ddns_passwords: "{{ vault_ddns_passwords }}"
ddns_domains: "{{ vault_ddns_domains }}"
ftp_host: "{{ vault_ftp_host }}"
ftp_user: "{{ vault_ftp_user }}"
ftp_password: "{{ vault_ftp_password }}"
telegram_bot_id: "{{ vault_telegram_bot_id }}"
telegram_chat_id: "{{ vault_telegram_chat_id }}"
telegram_user_id: "{{ vault_telegram_user_id }}"
domains: "{{ vault_domains }}"
binance_current_coin: "{{ vault_binance_current_coin }}"
binance_api_key: "{{ vault_binance_api_key }}"
binance_api_secret_key: "{{ vault_binance_api_secret_key }}"
default_mail: "{{ vault_default_mail }}"
photoprism_admin_password: "{{ vault_photoprism_admin_password }}"
photoprism_domain: "{{ vault_photoprism_domain }}"
photoprism_mysql_root_password: "{{ vault_photoprism_mysql_root_password }}"
photoprism_mysql_database: "{{ vault_photoprism_mysql_database }}"
photoprism_mysql_user: "{{ vault_photoprism_mysql_user }}"
photoprism_mysql_password: "{{ vault_photoprism_mysql_password }}"
cloud_domain: "{{ vault_cloud_domain }}"
cloud_admin_user: "{{ vault_cloud_admin_user }}"
cloud_admin_password: "{{ vault_cloud_admin_password }}"
cloud_redis_host_password: "{{ vault_cloud_redis_host_password }}"
cloud_mysql_root_password: "{{ vault_cloud_mysql_root_password }}"
cloud_mysql_database: "{{ vault_cloud_mysql_database }}"
cloud_mysql_user: "{{ vault_cloud_mysql_user }}"
cloud_mysql_password: "{{ vault_cloud_mysql_password }}"
cloud_mail_address: "{{ vault_cloud_mail_address }}"
cloud_mail_smtphost: "{{ vault_cloud_mail_smtphost }}"
cloud_mail_username: "{{ vault_cloud_mail_username }}"
cloud_mail_password: "{{ vault_cloud_mail_password }}"